config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :status, presence: true, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 255 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
              uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました！'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました！'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました！'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :show, :edit, :update]
  
  def index
    @tasks = current_user.tasks
  end
  
  def show
  end
 
  def new
    @task = current_user.tasks.build
  end   
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:sucess] = "保存されました！"
      redirect_to tasks_url
    else
      flash.now[:danger] = "保存されませんでした！"
      render :new
    end
    
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:sucess] ="更新されました！"
      redirect_to task_url(@task)
    else
      flash.now[:danger] = "更新されませんでした！"
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:sucess] = "削除されました！"
    redirect_to tasks_url
  
  end
  
  private 
  
  def task_params
    params.require(:task).permit(:content,:status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to "/"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = '登録に成功しました！'
      redirect_to tasks_path
    else
      flash.now[:danger] = '登録に失敗しました！'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_message" %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task ,local: true) do |f| %>
  
  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <%= f.label :content, "内容" %>
  <%= f.text_field :content %>
  
  <%= f.label :status, "ステータス" %>
  <%= f.text_field :status %>
  
  <%= f.submit "投稿" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

<%= render 'form', task: @task %>

<%= link_to "戻る", tasks_path %>

app/views/tasks/index.html.erb
<h1>やることリスト</h1>

  <p>ユーザー名：<%= current_user.name %></p>
  
  <ol>
    <% @tasks.each do |task| %>
    <li>
      <%= link_to task.content, task_path(task) %> &gt; <%= task.status %>
    </li>
    <% end %>

  </ol>
  <p><%= link_to "タスクを追加する", new_task_path %></p>
  <p><%= link_to "ログアウト", logout_path, method: :delete %></p>

app/views/tasks/new.html.erb
<h1>タスクの追加</h1>

<%= render 'form', task: @task %>

<%= link_to "戻る", tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>
  <p>内容：<%= @task.content %></p>
  <p>ステータス：<%= @task.status %></p>


<%= link_to "編集", edit_task_path(@task) %>
<%= link_to "削除", @task, method: :delete, data: {confirm: "本当に削除しますか？"} %>
<%= link_to "戻る", tasks_path %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with(model: @user ,local: true) do |f| %>
  
  <% if @user.errors.any? %>
      <div id="error_explanation">
          <ul>  
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
  <% end %>
    
  <p>
    <%= f.label :name, "ユーザー名" %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :email, "Email" %>
    <%= f.email_field :email %>
  </p>
  
  <p>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_confirmation, "パスワード確認" %>
    <%= f.password_field :password_confirmation %>
  </p>
  
  <p>
    <%= f.submit "登録" %>
  </p>
  
  <p><%= link_to '戻る', root_path %></p>


<% end %>